version: '3.6'

services:
  api:
    image: node:18-alpine
    container_name: tqd-node
    build: .
    ports:
      - 3002:3002
    environment:
      - NODE_ENV=local
      - ES_HOST=elasticsearch
      - NODE_PORT=3002
      - ELASTIC_URL=http://elasticsearch:9200
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - esnet

  elasticsearch:
    container_name: tqd-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms1024m -Xmx1024m'
      - discovery.type=single-node
    logging:
      driver: none
    ports:
      - 9300:9300
      - 9200:9200
    networks:
      - esnet

volumes:
  esdata:

networks:
  esnet:
